@startuml "Query1: Scope(7), label_reg=P*D, label_order=D ＜ P, data_eq=x:int"
'skinparam linetype ortho
usecase "0" as scope_0
usecase "7" as scope_7
usecase "4" as scope_4
usecase "9" as scope_9
card "x: int" as scope_10
usecase "6" as scope_6
usecase "11" as scope_11
usecase "8" as scope_8
card "x: int" as scope_2
usecase "1" as scope_1
card "x: int" as scope_5
card "x: bool" as scope_3
scope_7 -u-> scope_6 : Parent
scope_4 --> scope_5 : Declaration
scope_4 -u-> scope_1 : Parent
scope_9 --> scope_10 : Declaration
scope_9 -u-> scope_4 : Parent
scope_6 -u-> scope_4 : Parent
scope_11 -u-> scope_9 : Parent
scope_8 -u-> scope_6 : Parent
scope_1 --> scope_2 : Declaration
scope_1 --> scope_3 : Declaration
scope_1 -u-> scope_0 : Parent


scope_7 --> scope_6 #red;line.dashed : P
scope_6 --> scope_4 #red;line.dashed : P
scope_4 --> scope_5 #red;line.dashed : D

scope_7 --> scope_6 #blue;line.dashed : P
scope_6 --> scope_4 #blue;line.dashed : P
scope_4 --> scope_5 #blue;line.dashed : D
@enduml