---
title: output
---
flowchart LR
    scope_0(("0"))
    scope_1(("1"))
    scope_2(("2"))
    scope_3["x: num"]
    scope_4["y: bool"]
    scope_5["r: REC(2)"]
    scope_6(("6"))
    scope_7["a: num"]
    scope_8(("8"))
    scope_9(("9"))
    scope_10(("10"))
    scope_11["z: num"]
    scope_12["x: bool"]
    scope_13["q: REC(9)"]
    scope_14(("14"))
    scope_15["b: bool"]
    scope_16(("16"))
    scope_17(("17"))
    scope_18(("18"))
    scope_19["z: num"]
    scope_20["p: num"]
scope_1 ==>|"Parent"| scope_0
scope_1 ==>|"Declaration"| scope_5
scope_2 ==>|"Declaration"| scope_4
scope_2 ==>|"Declaration"| scope_3
scope_6 ==>|"Parent"| scope_1
scope_6 ==>|"Declaration"| scope_7
scope_8 ==>|"Parent"| scope_6
scope_8 ==>|"Declaration"| scope_13
scope_9 ==>|"Record"| scope_10
scope_9 ==>|"Extension"| scope_2
scope_10 ==>|"Declaration"| scope_11
scope_10 ==>|"Declaration"| scope_12
scope_14 ==>|"Parent"| scope_8
scope_14 ==>|"Declaration"| scope_15
scope_16 ==>|"Parent"| scope_14
scope_16 ==>|"Declaration"| scope_20
scope_17 ==>|"Parent"| scope_14
scope_17 ==>|"Record"| scope_9
scope_18 ==>|"Parent"| scope_17
scope_18 ==>|"Declaration"| scope_19
scope_5 ==>|"(Rec)"| scope_2
scope_13 ==>|"(Rec)"| scope_9
