[package]
name = "scope-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
plantuml = {path = "../plantuml"}
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
criterion = "0.5.1"
scopegraphs = "0.3.3"

[[bench]]
name = "sg-construction"
harness=false
