[package]
name = "scope-graph"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
graphing = {path = "../graphing"}
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
criterion = "0.5.1"
scopegraphs = "0.3.3"

[[bench]]
name = "sg-construction"
harness=false
