[package]
name = "graphing"
version = "0.1.0"
edition = "2024"

[features]
plantuml = []
mermaid = []

[dependencies]
derive_more = {version = "2.0.1", features = ["display"]}
tracing = {workspace = true}